// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vlijzstztuteysfayhsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaWp6c3R6dHV0ZXlzZmF5aHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjUxOTQsImV4cCI6MjA3MTU0MTE5NH0.p_HGWEpH-WufOPWoEztWm3gzQKEZp9MsgaRW4nZ5dCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);